### PR TITLE
Revert "[Fix] Make voltdb work after a reboot in the cleanup script."

### PR DESCRIPTION
**Pull request by paul-amonson**
This reverts commit a1dc7d5c8d27f34853325936bafc000473149951.

### CODE REVIEW

**Review by nbwhite — COMMENTED** [review]
You could revert this, or you should be able to fix the issue with something like this:

sudo sh -c 'echo never >/sys/kernel/mm/transparent_hugepage/enabled'

**Review by avincigu — APPROVED** [review]

**Comment by paul-amonson** [comment]
> You could revert this, or you should be able to fix the issue with something like this:
> 
> sudo sh -c 'echo never >/sys/kernel/mm/transparent_hugepage/enabled'

The problem was that sudo was failing to elevate far enough. I have seen this before sudo is not always equal to root privileges. The line I had works on Ubuntu but apparently not openSUSE. Rather than "tailor" a fix to one OS, I will handle this in the environments.

**Review by nbwhite — APPROVED** [review]
After conversation, I'm fine moving this into the documentation for  installation

**Comment by cmcheung-UCS** [comment]
What does it mean to sudo in a docker or VM to change kernel settings?

**Pull request merged**
