### PR TITLE
Readability for hw info.

### PR DESCRIPTION
**Pull request by cmcheung-UCS**
Signed-off-by: Ming Cheung <chi.m.cheung@intel.com>

### CODE REVIEW

**Review by avincigu — CHANGES_REQUESTED** [review]
I think this change will break the python tests.  Make sure all tests in python3 -m pytest . --cov-config .coveragerc --cov=cli --cov-report term-missing --cov-report xml:results.xml --cov-report html:coverage-report.xml --fulltrace
are passing before pushing changes.

**Comment by paul-amonson** [comment]
> I think this change will break the python tests. Make sure all tests in python3 -m pytest . --cov-config .coveragerc --cov=cli --cov-report term-missing --cov-report xml:results.xml --cov-report html:coverage-report.xml --fulltrace
> are passing before pushing changes.

So I tried that commandline as a precurser to adding this to the build/test process in gradle but all I get is:
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --cov-config .coveragerc --cov=cli --cov-report term-missing --cov-report xml:results.xml --cov-report html:coverage-report.xml
  inifile: None
  rootdir: /home/pdamons/Code/dai-ds

Any ideas?

**Comment by cmcheung-UCS** [comment]
The following works
task('pytest', type: Exec) {
    workingDir 'cli'
    commandLine 'pytest', '.',
            '--cov-config=.coveragerc --cov=cli --cov-report term-missing --cov-report xml:results.xml --cov-report',
            'html:coverage-report.xml --fulltrace'
}

You need to install

  *   pytest
  *   mock
  *   timeout_decorator
  *   pytest-cov

**Review by sindhu-106 — APPROVED** [review]

**Comment by paul-amonson** [comment]
My new RPMs branch will add a testPython task for running the python UT w/ coverage. If travis CI works I will make this automatic with a build, if not you need to run "./gradlew testPython" to manually run the task. I am having trouble getting travis CI to execute my branch, the queue is very long apparently.

**Comment by paul-amonson** [comment]
> My new RPMs branch will add a testPython task for running the python UT w/ coverage. If travis CI works I will make this automatic with a build, if not you need to run "./gradlew testPython" to manually run the task. I am having trouble getting travis CI to execute my branch, the queue is very long apparently.

Ok, travis CI fails so this has to be a new manual task.

**Review by sindhu-106 — APPROVED** [review]

**Review by avincigu — APPROVED** [review]

**Pull request merged**
