### PR TITLE
[Fix] Updated configurations for TDS.

### PR DESCRIPTION
**Pull request by paul-amonson**
Signed-off-by: Paul Amonson <paul.d.amonson@intel.com>

### CODE REVIEW

**Review by nbwhite — CHANGES_REQUESTED** [review]
Can you add the AvroDeserializer to the Inventory Provider?

**Comment by paul-amonson** [comment]
> 

I will not do this until we can verify that AVRO is used on the TDS install.

**Comment by paul-amonson** [comment]
> > 
> 
> I will not do this until we can verify that AVRO is used on the TDS install.

Since you are insisting...I when and looked. Unless you mean something completely different, the AVRO is already set as the deserializer. What is being asked here?

**Comment by nbwhite** [comment]
> > > 
> > 
> > 
> > I will not do this until we can verify that AVRO is used on the TDS install.
> 
> Since you are insisting...I when and looked. Unless you mean something completely different, the AVRO is already set as the deserializer. What is being asked here?

Ah, I had to expand out the review one more time to see the Deserializer. We are all good.

**Review by nbwhite — APPROVED** [review]

**Review by avincigu — APPROVED** [review]

**Pull request merged**
